CREATE DATABASE TheFoodApp;
USE TheFoodApp;

CREATE TABLE FA_RESTORANTS (
ID int NOT NULL PRIMARY KEY AUTO_INCREMENT,

FA_Email varchar(100) NOT NULL unique,
FA_Pass varchar(100) NOT NULL,

FA_Token varchar(100) NOT NULL DEFAULT '0'
);

CREATE TABLE FA_MENUS (
FA_Order int NOT NULL PRIMARY KEY AUTO_INCREMENT,
RESTAURANT_ID int(11) NOT NULL,

FA_Product_Name varchar(200) NOT NULL,
FA_Price double NOT NULL,
FA_Desc varchar(200),
FA_Contents varchar(200),

FOREIGN KEY (RESTAURANT_ID) REFERENCES FA_RESTORANTS(ID)
);
